In [218]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn import tree

fullFilename = 'C:/Users/Zander/Desktop/Decision_Tree/Garmin_Health_Data.csv'
health_data = pd.read_csv(fullFilename,sep =';', header=0)

In [219]:
print("Datatset:: ")
health_data.head()

Datatset:: 


Average_Resting  Average_HRV  Avergage_Resting_Week1  Avergage_HRV_Week1  \
0               55           90                      60                  92   
1               61           82                      72                  75   
2               54           70                      50                  72   
3               59           87                      70                  85   
4               71           91                      75                  75   

   Avergage_Resting_Week2  Avergage_HRV_Week2  Classfication  
0                      62                  89              0  
1                      75                  72              1  
2                      52                  69              0  
3                      69                  83              0  
4                      69                  79              0

In [220]:
from sklearn.model_selection import train_test_split
X = health_data.values[:, 0:5]
Y = health_data.values[:, 6]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)
Depression_Entropy = DecisionTreeClassifier(criterion = "entropy", max_depth=5)
Depression_Entropy.fit(X_train,Y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5)

In [221]:
Depression_Entropy.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'entropy',
 'max_depth': 5,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': None,
 'splitter': 'best'}

In [222]:
#Prediction
Y_pred_en = Depression_Entropy.predict(X_test)
Y_pred_en

array([1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0], dtype=int64)

In [223]:
X_test

array([[ 55, 103,  72,  97,  73],
       [ 56, 111,  56, 115,  61],
       [ 64,  83,  84,  77,  74],
       [ 65,  74,  70,  77,  76],
       [ 53, 101,  71,  94,  67],
       [ 80, 106,  84, 107,  92],
       [ 71, 102,  89,  93,  84],
       [ 70,  76,  78,  77,  87],
       [ 54, 115,  64, 107,  74],
       [ 64, 109,  65, 113,  72],
       [ 72,  95,  91,  87,  89],
       [ 67,  84,  75,  88,  79],
       [ 59,  82,  71,  73,  72],
       [ 75, 110,  87, 103,  90],
       [ 68,  79,  83,  70,  84],
       [ 57, 108,  61, 108,  63],
       [ 68,  94,  70,  96,  70],
       [ 77,  89,  77,  92,  82],
       [ 79,  78,  80,  78,  86],
       [ 52, 101,  54, 102,  56],
       [ 59,  87,  70,  85,  69],
       [ 58,  95,  64,  96,  70],
       [ 56,  73,  73,  63,  73],
       [ 57,  72,  67,  67,  76],
       [ 58, 113,  72, 106,  70],
       [ 78,  89,  90,  83,  90],
       [ 54,  86,  67,  81,  68],
       [ 66,  70,  72,  74,  79],
       [ 77,  88,  94,  83,  94],
       [ 64, 1

In [224]:
#Accuracy Score
print("Accuracy is ", accuracy_score(Y_test,Y_pred_en)*100)  

Accuracy is  79.56204379562044


In [217]:
#Probibilities
Depression_Entropy.predict_proba(X_test)

array([[1.        , 0.        ],
       [0.        , 1.        ],
       [0.64125561, 0.35874439],
       [0.        , 1.        ],
       [0.64125561, 0.35874439],
       [0.64125561, 0.35874439],
       [0.03773585, 0.96226415],
       [1.        , 0.        ],
       [0.64125561, 0.35874439],
       [0.        , 1.        ],
       [0.        , 1.        ],
       [1.        , 0.        ],
       [0.64125561, 0.35874439],
       [0.        , 1.        ],
       [0.64125561, 0.35874439],
       [0.        , 1.        ],
       [0.64125561, 0.35874439],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.64125561, 0.35874439],
       [0.        , 1.        ],
       [0.64125561, 0.35874439],
       [0.03773585, 0.96226415],
       [0.57446809, 0.42553191],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.64125561, 0.35874439],
       [1.        , 0.        ],
       [0.64125561, 0.35874439],
       [0.64125561, 0.35874439],
       [1.

In [225]:
#Wrongly classified instances
confusion_matrix(Y_test,Y_pred_en, labels= [0,1])

array([[53, 22],
       [ 6, 56]], dtype=int64)

In [226]:
#Precision Score
precision_score(Y_test,Y_pred_en)

0.717948717948718

In [227]:
Depression_Entropy.feature_importances_

array([0.3544615 , 0.        , 0.60123814, 0.02980764, 0.01449272])